application setup
MyskinD/chocolate-factory pull request #2
Opened 2020-01-28 22:26 UTC by MyskinD

2020-01-29 08:42 UTC, Sharykhin requested changes

2020-01-29 08:42 UTC, Sharykhin commented on .gitignore
> +nbproject
видишь, гит показывает, и это правильно, что файл должен заканчиваться, пустой строкой

2020-01-29 08:42 UTC, Sharykhin commented on app/Http/Controllers/StuffController.php
> +}
видишь, гит показывает, и это правильно, что файл должен заканчиваться, пустой строкой

2020-01-29 08:42 UTC, Sharykhin commented on app/Http/Controllers/StuffController.php
> +
лишние пробелы, учись писать красиво сразу, а не откладывая на потом, это должно быть, как привычка, писать красиво

2020-01-29 08:42 UTC, Sharykhin commented on app/Http/Middleware/ForceJsonResponse.php
> +
лишняя пустая строка

2020-01-29 08:42 UTC, Sharykhin commented on app/Providers/AppServiceProvider.php
> +        Schema::defaultStringLength(191);
а это что за дичь и зачем она тут нужна?

2020-01-29 08:42 UTC, Sharykhin commented on app/Services/StuffServices.php
> +}
пустая строка

2020-01-29 08:42 UTC, Sharykhin commented on database/migrations/2020_01_11_064705_create_stuffs_table.php
> +            $table->engine = 'InnoDB';
этого не надо, инно дб в мускуле по-умолчанию выбирается

2020-01-29 08:42 UTC, Sharykhin commented on database/migrations/2020_01_11_064705_create_stuffs_table.php
> +            $table->string('email')->unique();
а где длина на емелй?

2020-01-29 08:42 UTC, Sharykhin commented on database/migrations/2020_01_11_064705_create_stuffs_table.php
> +            $table->bigIncrements('id');
он создает праймари ключ?

2020-01-29 08:42 UTC, Sharykhin commented on app/Models/Stuff.php
> +class Stuff extends Model
в лавре, чтобы ide подсвечивавла свойства их описывают аннотациями как комментарии
```php
/**
 * @property int $id
 * @property string $first_name
 */
class Stuff extends Model
```

вот таким вво образом описывай свйоства

2020-01-29 08:42 UTC, Sharykhin commented on resources/sass/app.scss
> -// Fonts
пока не пойму, почему ты вообще насиловвал эти файлы стилей и жз, мы фронт не собираемся пока делать, особенно на лавре

2020-01-29 08:42 UTC, Sharykhin commented on routes/api.php
> +});
пустя строка

2020-01-29 08:42 UTC, Sharykhin commented on routes/api.php
> +Route::group(['middleware' => 'app'], function ()
а что за миддлвее app?

2020-01-29 08:42 UTC, Sharykhin commented on routes/api.php
> +    Route::match(['get', 'post'], 'stuffs', ['uses' => 'StuffController@Stuffs', 'as' => 'stuffs']);
а почему и гет и пост на один и тот екшн? и почему екшн с Большой буквы?

2020-01-29 19:42 UTC, MyskinD commented on app/Providers/AppServiceProvider.php
> +        Schema::defaultStringLength(191);
эта дичь помогает работать с базой данных вроде. уже не помню. но я нагуглил эту дичь, и она помогла

2020-01-29 19:46 UTC, Sharykhin commented on app/Providers/AppServiceProvider.php
> +        Schema::defaultStringLength(191);
Нет, не может она помогать, я такое впервые вижу, и у меня нет никаких проблем. Да и ты уже взрослый, видешь какую-то шнягу, которая выставляет дефолтную длину в 191? Как бы у тебя самого не возникает вопрос: что блять тут происходит?

2020-01-30 06:44 UTC, Sharykhin requested changes

2020-01-30 06:44 UTC, Sharykhin commented on app/Http/Controllers/StuffController.php
> +        StuffResource::withoutWrapping();
не наадо заниматься оверинженерингом, давай условимся, что все ответы должны быть в json-е
а то тут какие-то классы респонсов, у ларавела есть response()->json() который принимамет массив перывм паррамметром и статус код вторымм, вот, по сути дела что на текущем этапе уже можно использовать

2020-01-30 06:44 UTC, Sharykhin commented on app/Http/Resources/StuffResource.php
> +class StuffResource extends JsonResource
вообщем ты понял, удаляй нахуй этот бесполезный класс, пока не сможешь доказаать его полезность

2020-01-30 06:44 UTC, Sharykhin commented on app/Services/StuffServices.php
> +class StuffServices
а почему здесь Services во-множественном числе, когда тот же StuffController в единсвенном, блять, привееди все к одному стилю, раз контроллер в единсвенном, то и сервис тоже в единсвенном называй

2020-01-30 06:44 UTC, Sharykhin commented on database/migrations/2020_01_29_211232_create_stuffs_table.php
> +        Schema::create('stuffs', function (Blueprint $table) {
а где все мои предыдущие заамечания?

2020-01-30 06:54 UTC, Sharykhin requested changes

2020-01-30 06:54 UTC, Sharykhin commented on database/migrations/2020_01_29_211232_create_stuffs_table.php
> +            $table->string('email');
добаввь индекс уникальности

2020-01-30 06:54 UTC, Sharykhin commented on database/migrations/2020_01_29_211232_create_stuffs_table.php
> +            $table->bigIncrements('id');
убедись, что создактся праймари ключ

2020-01-30 06:54 UTC, Sharykhin commented on database/migrations/2020_01_29_211232_create_stuffs_table.php
> +            $table->string('password');
Хорошей практикой считается выставлять длину пароля, с учетом хер функции, к примеру bcrypt по-моему генерирует длину 80, чтобы создать дополнительный рестрикшн на уроввне базы

2020-01-30 18:21 UTC, MyskinD commented on app/Providers/AppServiceProvider.php
> +        Schema::defaultStringLength(191);
Возникает. но без этого нихрена не работает

2020-01-30 18:25 UTC, MyskinD commented on database/migrations/2020_01_29_211232_create_stuffs_table.php
> +            $table->bigIncrements('id');
что значит убедись? мне создать таблицу и посмотреть что там за ключ создался?

2020-01-31 08:27 UTC, Sharykhin commented on database/migrations/2020_01_29_211232_create_stuffs_table.php
> +            $table->bigIncrements('id');
да

2020-02-02 14:04 UTC, closed without merging