Cf 1
MyskinD/chocolate-factory pull request #3
Opened 2020-02-03 10:11 UTC by MyskinD

2020-02-06 18:23 UTC, Sharykhin requested changes

2020-02-06 18:23 UTC, Sharykhin commented on .gitignore
> +/.idea
этот путь некорректнйый, ты наверное имел ввилу ./idea

2020-02-06 18:23 UTC, Sharykhin commented on app/Api/Repositories/StuffRepository.php
> +}
добавь пустую строку, тебе же сам гит подсказывает, внимательней будь, 2500 не будут платить челловеку, который не проверяет свой же код

2020-02-06 18:23 UTC, Sharykhin commented on app/Api/Repositories/StuffRepositoryInterface.php
> +    public function add(array $data);
сверху у тебя возращаемый тип - `void` а тут нет, почему разные типы, тогда и сюда добавь void

2020-02-06 18:23 UTC, Sharykhin commented on app/Api/Services/StuffService.php
> +
что за лишняя строка, убирай
и добавь тип для `public function createStuff(array $data)` если это `void` то и добавляй void

2020-02-06 18:23 UTC, Sharykhin commented on app/Api/Validations/StuffValidation.php
> +}
добавь пустую строку блять!!!!!

2020-02-06 18:23 UTC, Sharykhin commented on app/Api/Validations/Validation.php
> +    protected function isNotNull(string $value, string $field): void
вообще по, так сказать бест практисес, когда метод начинается с isBlaBla то он проверят, а оно это или нет и, как правило возращает булево, у тебя тут либо пан либо пропал, и тогда методы лучше называть как глаголы, типо `validateOnNull` `validateRegExp`

2020-02-06 18:23 UTC, Sharykhin commented on app/Http/Controllers/Api/StuffController.php
> +}
добавь пустую строку блять

2020-02-06 18:23 UTC, Sharykhin commented on app/Http/Controllers/Api/StuffController.php
> +        } catch(Exception $exception) {
добавь обработку эексепшена, чтобы возращать 400 ответ

2020-02-06 18:23 UTC, Sharykhin commented on app/Http/Controllers/Api/StuffController.php
> +
а когда запись создана, тебе надо вернуть 201 ответ, и с новосозданным сотрудником, как в задании сказано

2020-02-06 18:23 UTC, Sharykhin commented on app/Api/Services/StuffService.php
> +        $this->stuffRepository->add($data);
а где шифрование пароля?)))))))))) получается ты его сохраняешь как есть?

2020-02-06 18:23 UTC, Sharykhin commented on app/Models/Stuff.php
> +class Stuff extends Model
добавь описание через @property как я тебе писал ранее

2020-02-06 18:23 UTC, Sharykhin commented on app/Providers/ApiServiceProvider.php
> +            'App\Api\Repositories\StuffRepositoryInterface',
лучше использовать конструкцию `\App\Api\Repositories\StuffRepositoryInterface::class` и так для всего
тогда в идэ можно легко перейти на сам класс

2020-02-06 18:23 UTC, Sharykhin commented on routes/api.php
> +Route::post('/stuff', [
В задании написано `stuffs` блять, там стоит `s`!!!! блять SSSSSSS

2020-02-10 21:25 UTC, MyskinD commented on app/Providers/ApiServiceProvider.php
> +            'App\Api\Repositories\StuffRepositoryInterface',
тут у меня не получилось сделать так, как ты предлагаешь.

2020-02-10 21:50 UTC, Sharykhin commented on app/Api/Services/StuffService.php
> +        if (is_null($newStuff)) {
у тебя в априоре не может быть null тут либо вернется объект класса Stuff либо будет какой-то ексепшен, поэтому данная проверка абсолютна бесполезна

2020-02-10 21:52 UTC, Sharykhin commented on app/Models/Stuff.php
> +        'created_at',
В лавре нет смысла добавлять эти свойства created_at и updated_at в филлабл, это то, что делает ларавел за тебя, и наличие их в $fillable только смущает
этот массив хранит те свойства, которые, по сути дела, если простым языком, ты можешь сетать вручную

2020-02-11 09:09 UTC, merged