added api versioningÐ
MyskinD/chocolate-factory pull request #5
Opened 2020-02-12 22:24 UTC by MyskinD

2020-02-12 22:27 UTC, MyskinD commented
ku

2020-02-13 08:40 UTC, Sharykhin commented on app/Api/Repositories/StuffRepositoryCreator.php
> +                break;
нахуй тут break если ты уже return вызвал?

2020-02-13 08:41 UTC, Sharykhin commented on app/Api/Repositories/StuffRepositoryCreator.php
> +                break;
нахуй тут break если ты уже throw вызвал

2020-02-13 09:02 UTC, Sharykhin commented on app/Providers/ApiServiceProvider.php
> -            \App\Api\Repositories\StuffRepositoryInterface::class,
вообщем так, версия апи не должна прокидывать ни в какие аргументы, все должно быть сделано тут
тебе нахуй не нужен твой RepositoryInterface
вот у тебя есть версия V1 и V2
вот значит, создаешь V1StuffRepository
создаещь интерфейс StuffRepositoyInteface
и в этом сервис провайдере смотришь., если в заголовке v1  значит привязываем первую версию
если v2 значит вторую
и уже везде, в сервисах контроллерах мы как радотали с абстракциями так и продолжаеем работать, мы не должны знать это версия 1 или 2, все разрулится сделсь
тоже самое касается сервисом

только если изменится интерфейс, тогда уже да, придется делать новую привязку
но пока у тебя интерфйс должен быть единым

2020-02-13 09:03 UTC, Sharykhin commented on app/Api/Repositories/StuffRepositoryCreator.php
> +            case 'v1' :
сами версии лучше вынести в конфиги, я думаю, или константы

2020-02-16 17:16 UTC, Sharykhin requested changes

2020-02-16 17:16 UTC, Sharykhin commented on app/Api/Models/StuffInterface.php
> +
лишняя пустая строка

2020-02-16 17:16 UTC, Sharykhin commented on app/Api/Models/V1Stuff.php
> +    public static $tableName = 'stuffs';
я не совсем понял, разве нужные две переменных table  и tableName, ставлю 10, что одна переменная лишняя

2020-02-16 17:16 UTC, Sharykhin commented on app/Api/Repositories/V1StuffRepository.php
>      public function get(int $id)
добавь возращаемый тип

2020-02-16 17:16 UTC, Sharykhin commented on app/Api/Repositories/V1StuffRepository.php
> +            ->get();
->get() вернет коллеуцию, но судя по семантике метода, он должен вернуть одну сущность(модель), что угодно, поэтому тут более уместно использовать first()

2020-02-16 17:16 UTC, Sharykhin commented on app/Api/Repositories/V1StuffRepository.php
> +            throw new NotFoundHttpException('Stuff was not found');
это можно поправить потом, но вообще, на будущее
у тебя эксепшен называется NotFoundHttpException и оно не совсем говорит о том, что именно не было найдено, плюс вот это слово http тоже не совсем уместно, а если мы будем использовать другой протокол, к примеру rpc, или grpc. Поэтому на самом деле надо будет в будущем создать более семантичные ексепшены

2020-02-16 17:16 UTC, Sharykhin commented on app/Api/Services/StuffServiceInterface.php
> +    public function get(int $id);
добавь возращаемый тип

2020-02-16 17:16 UTC, Sharykhin commented on app/Http/Controllers/Api/StuffController.php
> +            return response()->json($stuff, 201);
201 первый ответ? Шо курим господин?
Почитай какие ответы на что должны возращаться, в интернете море информации на это
201 - это ответ, когда ресурс создан
для просмотра - 200
Так что блять не ленись, достань член из песка и почитай, такие элементарные вщеи надо знать блять, как не знаю, как свой член

2020-02-16 17:16 UTC, Sharykhin commented on app/Api/Repositories/V1StuffRepository.php
> +        $stuff->role = $data['role'];
в сервисе нет валидации на роль

2020-02-17 07:39 UTC, MyskinD commented on app/Api/Models/V1Stuff.php
> +    public static $tableName = 'stuffs';
а как я обращусь к протектед переменной из репозитория?

2020-02-17 07:41 UTC, Sharykhin commented on app/Api/Models/V1Stuff.php
> +    public static $tableName = 'stuffs';
а тебе и не нужно напрямую обращаться к таблице
```new V1Stuff``` уже будет работтаь снужной таблицей
`V1Stuff::query()` уже будет ссылаться на нужную таблицу

2020-02-17 08:46 UTC, Sharykhin approved these changes

2020-02-17 08:46 UTC, merged