CF-3
MyskinD/chocolate-factory pull request #7
Opened 2020-02-18 10:20 UTC by MyskinD

2020-02-18 10:30 UTC, Sharykhin requested changes

2020-02-18 10:30 UTC, Sharykhin commented on app/Api/Models/V1Stuff.php
> +        'token'
а что делать, если мы авторизовываемся в друх броузерах, или, что более вероятно, в мобилке и в броузере на компе, все, получается пизда рулям, раз токен один, то в другом устройстве тебя автоматом вылогинит, что плохо

2020-02-18 10:30 UTC, Sharykhin commented on app/Api/Repositories/Contracts/StuffAuthInterface.php
> +    public function saveToken(Int $id, string $token): StuffInterface;
а почему Int с большой?

2020-02-18 10:30 UTC, Sharykhin commented on app/Api/Services/V1AuthService.php
> +        $secretKey = env('APP_KEY');
используй config  функцию так как функция env при переводе приложения в продакшн, перестает существовать и будет 500 ошибка, мол вызвали несуществующую функцию

2020-02-18 10:30 UTC, Sharykhin commented on app/Api/Services/V1AuthService.php
> +        ];
а что если, мы завтра решим использоватвь какую-нибудь красивую библиотеку для jwt, придется переписывать этот метод логин и его тесты, хотя мы могли бы вынести логику jwt в отдельный класс и создать интерфейс, и тогда, в случае чего, мы просто подменили бы релазицию

2020-02-18 10:30 UTC, Sharykhin commented on app/Http/Controllers/Api/AuthController.php
> +    public function login(Request $request)
Индекти заввисимости на уровне экшена а не контроллера

2020-02-18 10:30 UTC, Sharykhin commented on app/Http/Controllers/Api/AuthController.php
> +        } catch (Exception $exception) {
обработку 500 ошибки не делай, потом будет задача, так ты потеряешь трейс и не сможешь отдебажить

2020-02-18 10:30 UTC, Sharykhin commented on app/Http/Controllers/Api/StuffController.php
>              return response()->json($exception->getMessage(), 500);
аналогично

2020-02-18 13:51 UTC, MyskinD commented on app/Http/Controllers/Api/AuthController.php
> +    public function login(Request $request)
почему на уровне экшена в контроллере надо инжектить зависимость?

2020-02-18 13:53 UTC, MyskinD commented on app/Api/Models/V1Stuff.php
> +        'token'
я тебя не понимать. по апи авторизовались. получили токен. далее с токеном передаем следующие запросы по апи. после выхода, токен удаляется. вроде все норм. или токен можно обнулять спустя какое то время. браузеры то тут причем?

2020-03-02 07:02 UTC, Sharykhin requested changes

2020-03-02 07:02 UTC, Sharykhin commented on app/Api/Repositories/V1SessionRepository.php
> +    public function add(array $data)
где возращаемый тип?

2020-03-02 07:02 UTC, Sharykhin commented on app/Api/Repositories/V1StuffRepository.php
> +    public function get(int $id)
чего удалил возращаемый тип?
везде доллжно быть полное описание как входящих параметров, так и исходящих

2020-03-02 07:02 UTC, Sharykhin commented on app/Api/Repositories/V1StuffRepository.php
> +            ->where('password', md5($data['password']))
у тебя репозиторий отвечает за бизнес логику
а что если мы решим изменить алгоритм шифрования, будешь менять сам репозиторий, допустим
а что если, к примеру с 2020-05-05 мы переходим на bcrypt, как быть с теми кастомеерами, которые уже были созданы с md5? поэтому репозитоирй особо не должен паариться за бизнес логику, хеш должен формироваться на уровне выше и передоваться репозиторию

2020-03-02 07:02 UTC, Sharykhin commented on app/Api/Services/JwtService.php
> +    private $stuff;
почему private?? если не можешь аргментировать, используй  protected

2020-03-02 07:02 UTC, Sharykhin commented on app/Api/Services/JwtService.php
> +    private function getHeader(): string
почему метод привавтный? Если не можешь аргументировать, всегда используй protected

2020-03-02 07:02 UTC, Sharykhin commented on app/Api/Services/JwtService.php
> +        $payload = $this->getPayload(time() + 60 * 60 * 24 * 60);
время жизни должно быть вынесено в конфигурацию и перемменную окружения, чтобы мы могли быстро и легко его изменить

2020-03-02 07:02 UTC, Sharykhin commented on app/Api/Services/JwtService.php
> +    public function getAccessToken(V1Stuff $stuff): string
ты привязал всю реализацию к одной модели Stuff что делает твой сервис не гибким, а если мы заходим его использоввавть, к примеру для сторонних сервисов, или для админов, гораздо же проще передать сюдаа просто тот же самый пейлоуд и все, и нам модель уже не неужнаа и можем использоавть данные сервис где угодно

2020-03-02 07:02 UTC, Sharykhin commented on app/Api/Services/JwtService.php
> +        $payload = $this->getPayload(time() + 60 * 30);
аналогично

2020-03-02 07:02 UTC, Sharykhin commented on app/Api/Services/JwtService.php
> +    public function getRefreshToken(V1Stuff $stuff): string
ааналогично

2020-03-02 07:02 UTC, Sharykhin commented on app/Api/Services/V1AuthService.php
> +        if (is_null($stuff)) {
ты же в репозитории уже кидаешь ексепшен, у тебя не может быть null как возращаемый тип

2020-03-02 07:02 UTC, Sharykhin commented on app/Api/Services/V1AuthService.php
> +        if (count($this->sessionRepository->allById($stuff->id)) >= V1Session::SESSION_COUNT) {
чето тут я логики не понял, мол если чел авторизоавлся более 5-и раз удилть всего его токены?
а если я авторизовался в одном броузере, потом в вдругом, потом в мобилке, в планшете и решил на работе в броузере авторизовавться, а тут хуяк, и меня отовсюда разлогинивает, какая-то непонятная хуета

2020-03-02 22:27 UTC, MyskinD commented on app/Api/Services/V1AuthService.php
> +        if (count($this->sessionRepository->allById($stuff->id)) >= V1Session::SESSION_COUNT) {
так и есть. я сделал ограничение на количество сессий. больше 5 нельзя. Хуяк и разлогинивает везде, кроме последней сессии. Таким образом мы можем усилить защиту от хакеров. Если даже кто-то похитит токены, то это дополнительно будет мешать ему использовать их.

2020-03-02 23:40 UTC, MyskinD commented on app/Api/Services/V1AuthService.php
> +        if (is_null($stuff)) {
убрал, спасибо

2020-03-02 23:42 UTC, MyskinD commented on app/Api/Services/JwtService.php
> +    public function getAccessToken(V1Stuff $stuff): string
вот тут интересный вопрос. Я создал jwtService, который принимает данные, и создает jwt. Если сделать его универсальным, тогда мне надо сделать выборку в виде подготовленного массива, или DTO. Я не знаю что лучше.

2020-03-03 00:08 UTC, MyskinD commented on app/Api/Repositories/V1SessionRepository.php
> +    public function add(array $data)
с типами проблема, не могу понять почему.

2020-03-03 00:08 UTC, MyskinD commented on app/Api/Repositories/V1StuffRepository.php
> +    public function get(int $id)
с типами проблема, не могу понять почему.

2020-03-03 00:08 UTC, MyskinD commented on app/Api/Services/JwtService.php
> +    private $stuff;
+

2020-03-03 00:09 UTC, MyskinD commented on app/Api/Services/JwtService.php
> +        $payload = $this->getPayload(time() + 60 * 60 * 24 * 60);
+++

2020-03-03 00:09 UTC, MyskinD commented on app/Api/Services/JwtService.php
> +    private function getHeader(): string
+++

2020-03-03 06:45 UTC, Sharykhin requested changes

2020-03-03 06:45 UTC, Sharykhin commented on app/Api/Dto/Contracts/DtoInterface.php
> +interface DtoInterface
а зачем пустой интерфейс? в этом нет смысла, интерфейс должен описывать АПИ, в пустом виде он весьма бесполезен

2020-03-03 06:45 UTC, Sharykhin commented on app/Api/Repositories/Contracts/AuthInterface.php
> +    public function getStuffByEmailAndPassword(array $data): StuffInterface;
можешь оставить как есть, но вообще вот тебе совет на будущее, используй массивыв только тогда, когда без этого уже никак. К примеру, вот я тут у тебя как менеджер, тим лид, хуелид, я смотрю на входящие параметры, ввижу что это какая-то $data, но что за данные, я понятия нее имею, так как мне надо идти в реализацию, смотреть ВЕСЬ метод, чтобы понять, что туда нужно передать
но если бы ты к примеру заменил на 
`public function getStuffByEmailAndPassword(string $email, string $password): StuffInterface`
было бы понятно что передовать, семантикук этих параметров и их типы, контракт стал бы более сильным

2020-03-03 06:45 UTC, Sharykhin commented on app/Api/Repositories/V1SessionRepository.php
> +    public function allById(int $id)
название метода вообще вырви глаз, найти все по идентификатору, идентификатору кого??? сессий или сотрудника? непонятно
должно быть `allByStuffId`

2020-03-03 06:45 UTC, Sharykhin commented on app/Api/Repositories/V1SessionRepository.php
> +    public function remove(int $id): void
тоже самое, передается какой-то id но совсем непонятно, что это id сотрудника, а может это id самой сесии??
надо методы называть семантично, `removeByStuffID` или `removeStuff` или `clearStuffSessions`

2020-03-03 06:45 UTC, Sharykhin commented on app/Api/Services/V1AuthService.php
> +        if (count($this->sessionRepository->allById($stuff->id)) >= V1Session::SESSION_COUNT) {
ок, пусть будет как ты сказал

2020-03-03 06:45 UTC, Sharykhin commented on app/Api/Services/V1AuthService.php
> +        if (count($this->sessionRepository->allById($stuff->id)) >= V1Session::SESSION_COUNT) {
но так как бизнес логика этой проверкки лежит в этом сервисе, то и константу нужно объявить тут в модели она не имеет смысла, модель за эту бизнес логику не отвечает

2020-03-03 06:45 UTC, Sharykhin commented on app/Http/Controllers/Api/AuthController.php
> +            $auth = $authService->login($data);
я хочу, чтобы клиенту ты отдавал ключи не camelCase а snak_case

2020-03-03 06:45 UTC, Sharykhin commented on config/app.php
> +    'access_token_lifetime' => time() + 60 * 30,
используй переменные окружения
.env
env('ACCESS_TOKEN_LIFETIME)
так мы можем контролировать время жизни для разных окружеий, для девелопа - там 10 дней, для продакшена 40 минут и тоже самое всех других значений secret_key, refresh_token_lifetime

2020-03-03 23:35 UTC, MyskinD commented on app/Api/Services/V1AuthService.php
> +        if (count($this->sessionRepository->allById($stuff->id)) >= V1Session::SESSION_COUNT) {
+++

2020-03-03 23:41 UTC, MyskinD commented on config/app.php
> +    'access_token_lifetime' => time() + 60 * 30,
+++

2020-03-03 23:51 UTC, MyskinD commented on app/Api/Dto/Contracts/DtoInterface.php
> +interface DtoInterface
добавил в интерфейс константу

2020-03-04 00:04 UTC, MyskinD commented on app/Api/Repositories/V1SessionRepository.php
> +    public function allById(int $id)
+++

2020-03-05 08:39 UTC, Sharykhin requested changes

2020-03-05 08:39 UTC, Sharykhin commented on app/Api/Dto/Contracts/DtoInterface.php
> +    public const MAX_ACTIVE_SESSION = 5;
опять нарушил семантику, интерфейс не о чем не говорит, и эта константа тут тоже ВВООБЩЕ ни о чем не говорит, не несет никакой смысловой нагрузки, дай этот код любому человеку и он не поймет, что это константа тут вообще делает, скорее всего подумает, что мертвывй код

2020-03-05 08:39 UTC, Sharykhin commented on app/Api/Services/V1AuthService.php
> +        if ($this->sessionRepository->countByStuffId($stuff->id) >= $stuffDto::MAX_ACTIVE_SESSION) {
Говорил же блять, где бизнес логика там и правила
MAX_ACTIVE_SESSION
это бизнес правило данного серввиса и константа должна быть тоже тут а не в ебенях где0то

2020-03-06 23:15 UTC, MyskinD commented on app/Api/Services/V1AuthService.php
> +        if ($this->sessionRepository->countByStuffId($stuff->id) >= $stuffDto::MAX_ACTIVE_SESSION) {
перенес

2020-03-06 23:16 UTC, MyskinD commented on app/Api/Dto/Contracts/DtoInterface.php
> +    public const MAX_ACTIVE_SESSION = 5;
убрал

2020-03-06 23:30 UTC, MyskinD commented on app/Api/Repositories/Contracts/AuthInterface.php
> +    public function getStuffByEmailAndPassword(array $data): StuffInterface;
+++

2020-03-06 23:33 UTC, MyskinD commented on app/Api/Repositories/V1SessionRepository.php
> +    public function remove(int $id): void
+++

2020-03-10 09:48 UTC, Sharykhin commented on app/Api/Repositories/Contracts/SessionRepositoryInterface.php
> +    public function add(array $data): Model;
а зачем возращать на столкьо абстрактный тип, он же бесполезен, тут уже или интерфейс возращай или забей

2020-03-10 09:49 UTC, Sharykhin commented on app/Api/Repositories/V1SessionRepository.php
> +        if (is_null($session)) {
бесполезнпя проверка, оно или пан или пропал, нет смысла проверять, в этот иф блок ты никогда не попадешь

2020-03-10 09:50 UTC, Sharykhin commented on app/Api/Repositories/V1SessionRepository.php
> +    public function getStuffIdByToken(string $token): Model
ты возращаешь только id? как я вижу ты возращаешь модель, а не одной единственное свойство
тут уже  надо писать getStuffByToken

2020-03-10 09:50 UTC, Sharykhin commented on app/Api/Repositories/V1SessionRepository.php
> +            throw new NotFoundHttpException('Session was not created');
что за дичь? `Session was not created` при чем тутс оздание?

2020-03-10 09:51 UTC, Sharykhin commented on app/Api/Repositories/V1StuffRepository.php
> +        if (is_null($stuff)) {
убирай проверку

2020-03-10 09:52 UTC, Sharykhin commented on app/Api/Services/V1AuthService.php
> +        $this->sessionRepository->add([
что за разные стили, ты уже определись, у тебя массивы с камелкейс или нижнем регистре

2020-03-10 09:53 UTC, Sharykhin commented on app/Http/Middleware/CheckToken.php
> +            return response()->json($exception->getMessage(), 404);
если токен не найден, то ты уже не аутентифицирован поэтому это статус код 401

2020-03-10 09:53 UTC, Sharykhin commented on app/Http/Middleware/CheckToken.php
> +            return response()->json($exception->getMessage(), 404);
второе, допустим ты нашел по токену сотрудника, а где проверка, что токен еще не заекспайрился?

2020-03-12 08:36 UTC, MyskinD commented on app/Api/Repositories/V1SessionRepository.php
> +            throw new NotFoundHttpException('Session was not created');
copy past ебаный

2020-03-12 08:36 UTC, MyskinD commented on app/Api/Repositories/V1SessionRepository.php
> +    public function getStuffIdByToken(string $token): Model
+++

2020-03-12 08:36 UTC, MyskinD commented on app/Api/Repositories/V1SessionRepository.php
> +        if (is_null($session)) {
+++

2020-03-15 17:46 UTC, MyskinD commented on app/Api/Repositories/Contracts/SessionRepositoryInterface.php
> +    public function add(array $data): Model;
забил

2020-03-15 17:47 UTC, MyskinD commented on app/Api/Repositories/V1StuffRepository.php
> +        if (is_null($stuff)) {
убрал нах

2020-03-15 17:50 UTC, MyskinD commented on app/Api/Services/V1AuthService.php
> +        $this->sessionRepository->add([
победила деревня из camelCase

2020-03-15 17:51 UTC, MyskinD commented on app/Http/Controllers/Api/AuthController.php
> +            $auth = $authService->login($data);
чо блять? Деревня из camelCase одержала победу. говорил же выше

2020-03-16 10:58 UTC, Sharykhin commented on app/Api/Repositories/V1SessionRepository.php
> +    public function removeByJwt(string $jwt): void
по семантике, этот метод лучше назвать removeByTOken так как нет гарантии, что мы точно и всегда будем работать именно с JWT

2020-03-16 10:59 UTC, Sharykhin commented on app/Api/Repositories/V1SessionRepository.php
> +    public function getStuffByToken(string $jwt = null)
тоже самое, тут лучже уже назвать переменную $accessToken

2020-03-16 11:00 UTC, Sharykhin commented on app/Api/Repositories/V1SessionRepository.php
> +    public function getStuffByToken(string $jwt = null)
а еще, что за бред, ты принимаешь null и при этом сразу проверяешь, что если это null кидать эксепшн, ты наркоман, что курим, чернозем?

2020-03-16 11:03 UTC, Sharykhin commented on app/Api/Services/JwtService.php
> +        if ((int) $lifetime < time()) {
а нахуя принимать строку и приводить ее к числу, почему бы сразу не принимать число, как таймстамп?
или тогда принмать тип DateTime и у него вызывать метод timestamp

2020-03-16 11:05 UTC, Sharykhin commented on app/Api/Services/JwtService.php
> +    public function checkTokenLifetime(string $lifetime): bool
вот опять семантика
checkTokenLifetime
переводим - проверить время жизни токена
и возращает true, или false
а что это значт, что типо было проверено, или не было проверено? вот из названия нихуя не понятно
а вот если бы ты назвали, к примеру isTokenExpired
тогда понятно, переводится, а заикспарился ли токен, и тут очевидно true- да, заекспарился, false - нет

2020-03-16 11:06 UTC, Sharykhin commented on app/Http/Controllers/Api/AuthController.php
> +            $auth = $authService->login($data);
наркоман???

2020-03-16 11:08 UTC, Sharykhin commented on app/Http/Controllers/Api/AuthController.php
> +            $auth = $authService->login($data);
ну сконвертируй данные
$response = [
'access_token' => $auth['accessToken']
....
];

2020-03-16 11:10 UTC, Sharykhin commented on app/Http/Middleware/CheckToken.php
> +                throw new NotFoundHttpException('Session was not found');
вот тут лучше кидать ошибку, что токен заекспарился, но это мелочь, просто чтобы ты знал

2020-03-16 11:13 UTC, Sharykhin commented on app/Http/Middleware/CheckToken.php
> +    public function handle($request, Closure $next)
ну и в идеале, тебе конечно нужно проверить, а вообще валиден ли токен само по себе
так как, я могу же сформировать свой токен, используя тот же jwt.io сайт, и указать время жизни до 2030 года

тобишь тебе надо сформировать токен используйя первую и вторую часть, и проверить, что третья часть. сигнатура - совпадает с тем, что передал в третьей части клиент

2020-03-16 20:27 UTC, MyskinD commented on app/Api/Repositories/V1SessionRepository.php
> +    public function removeByJwt(string $jwt): void
+++

2020-03-16 20:29 UTC, MyskinD commented on app/Api/Repositories/V1SessionRepository.php
> +    public function getStuffByToken(string $jwt = null)
сам ты наркоман.
я принимаю токен, а если я его не передам, то будет null по умолчанию. и проверка на нулл выкинет исключение

2020-03-16 20:39 UTC, MyskinD commented on app/Api/Repositories/V1SessionRepository.php
> +    public function getStuffByToken(string $jwt = null)
поправил!

2020-03-16 20:44 UTC, MyskinD commented on app/Api/Services/JwtService.php
> +    public function checkTokenLifetime(string $lifetime): bool
++

2020-03-16 20:45 UTC, MyskinD commented on app/Api/Services/JwtService.php
> +        if ((int) $lifetime < time()) {
так я $lifetime принимаю из токена! это строка!

2020-03-16 20:56 UTC, MyskinD commented on app/Http/Middleware/CheckToken.php
> +    public function handle($request, Closure $next)
точняк, надо проверить!

2020-03-18 10:16 UTC, merged